import Head from 'next/head'
import styles from './MainLayout.module.css'
import { Navbar } from '@/components/Navbar'

type Props = {
    children: JSX.Element | JSX.Element[]
}

export const MainLayout = ({ children }: Props) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Home - Garias</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main className={`${styles.main}`}>
                {
                    children
                }
            </main>
        </div>
      )
}
